# Generated by Django 3.2.8 on 2021-10-26 19:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=50)),
                ('specialistion', models.CharField(max_length=30)),
                ('degree_name', models.CharField(max_length=30)),
                ('internship_applied', models.CharField(max_length=100)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_id', models.EmailField(max_length=100)),
                ('location', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=30)),
                ('notes', models.TextField()),
            ],
        ),
    ]
