# Generated by Django 3.2.8 on 2021-10-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
    ]
