# Generated by Django 3.2.8 on 2021-10-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_tbl_student_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_student',
            old_name='specialistion',
            new_name='specialisation',
        ),
    ]
